### ISSUE TITLE
Add model generator for FluentHub.Octokit

### ISSUE THREAD

**Issue by onein528** [FluentHub/FluentHub#195]
### ⏱️ Before you start...

- [X] Have you checked if a similar tracker has already been reported?

### 🛤️ Feature

As "Octokit.GraphQL.NET" is a non-maintained project, we have to take multiple actions.

- [x] Fork it into this organization
- [ ] Add its fork to this as a submodule(by doing so, don't have to use its official package and we can maintain with our hands when we wanna maintain).
- [ ] Add schema generator for FluentHub.Octokit (difficult thing)

### 📄 Description

As I told in Feature section.

**Comment by DeveloperWOW64** [comment]
ooooooooo!

**Comment by DeveloperWOW64** [comment]
WDYM schema gen?

**Comment by onein528** [comment]
See [Models](https://github.com/FluentHub/FluentHub/tree/main/src/FluentHub.Octokit/Models) which I create manually.

This folder is for the [GraphQL schema](https://docs.github.com/en/graphql/overview/public-schema).
